.pragma library
var data = {
    "search_placeholder": {
        "en": "Search the web...",
        "tr": "Arama_Yapmak_İçin_Yazın",
        "de": "Im Web suchen...",
        "fr": "Rechercher sur le web...",
        "it": "Cerca nel web...",
        "es": "Buscar en la web...",
        "pt": "Pesquisar na web...",
        "ru": "Поиск в интернете...",
        "ja": "ウェブを検索...",
        "zh": "搜索网络...",
        "el": "Αναζήτηση στο διαδίκτυο...",
        "az": "Vebdə axtar...",
        "hy": "Որdelays delays համdelays...",
        "ro": "Caută pe web...",
        "cs": "Hledat na webu...",
        "hi": "वेब पर खोजें...",
        "bn": "ওয়েবে অনুসন্ধান করুন...",
        "ur": "ویب پر تلاش کریں...",
        "id": "Cari di web...",
        "fa": "جستجو در وب..."
    },
    "incognito": {
        "en": "Open Incognito Window",
        "tr": "Gizli Pencere Aç",
        "de": "Inkognito-Fenster öffnen",
        "fr": "Ouvrir une fenêtre privée",
        "it": "Apri finestra in incognito",
        "es": "Abrir ventana de incógnito",
        "pt": "Abrir janela anônima",
        "ru": "Открыть инкогнито",
        "ja": "シークレットウィンドウを開く",
        "zh": "打开隐身窗口",
        "el": "Άνοιγμα ανώνυμου παραθύρου",
        "az": "Gizli pəncərə aç",
        "hy": "Բdelays delays delays",
        "ro": "Deschide fereastră privată",
        "cs": "Otevřít anonymní okno",
        "hi": "गुप्त विंडो खोलें",
        "bn": "গোপন উইন্ডো খুলুন",
        "ur": "پوشیدہ ونڈو کھولیں",
        "id": "Buka jendela penyamaran",
        "fa": "باز کردن پنجره ناشناس"
    },
    "new_tab": {
        "en": "Open New Tab",
        "tr": "Yeni Sekme Aç",
        "de": "Neuer Tab öffnen",
        "fr": "Ouvrir un nouvel onglet",
        "it": "Apri nuova scheda",
        "es": "Abrir nueva pestaña",
        "pt": "Abrir nova aba",
        "ru": "Открыть новую вкладку",
        "ja": "新しいタブを開く",
        "zh": "打开新标签页",
        "el": "Άνοιγμα νέας καρτέλας",
        "az": "Yeni tab aç",
        "hy": "Բdelays delays delays",
        "ro": "Deschide tab nou",
        "cs": "Otevřít novou kartu",
        "hi": "नया टैब खोलें",
        "bn": "নতুন ট্যাব খুলুন",
        "ur": "نیا ٹیب کھولیں",
        "id": "Buka tab baru",
        "fa": "باز کردن تب جدید"
    },
    "history": {
        "en": "Open History",
        "tr": "Geçmişi Aç",
        "de": "Verlauf öffnen",
        "fr": "Ouvrir l'historique",
        "it": "Apri cronologia",
        "es": "Abrir historial",
        "pt": "Abrir histórico",
        "ru": "Открыть историю",
        "ja": "履歴を開く",
        "zh": "打开历史记录",
        "el": "Άνοιγμα ιστορικού",
        "az": "Tarixçəni aç",
        "hy": "Բdelays պdelays",
        "ro": "Deschide istoricul",
        "cs": "Otevřít historii",
        "hi": "इतिहास खोलें",
        "bn": "ইতিহাস খুলুন",
        "ur": "تاریخ کھولیں",
        "id": "Buka riwayat",
        "fa": "باز کردن تاریخچه"
    },
    "dino_game": {
        "en": "Play Dino Game",
        "tr": "Dinazor Oyunu Oyna",
        "de": "Dino-Spiel spielen",
        "fr": "Jouer au jeu Dino",
        "it": "Gioca a Dino Game",
        "es": "Jugar al juego del dinosaurio",
        "pt": "Jogar o jogo do Dinossauro",
        "ru": "Играть в Дино",
        "ja": "恐竜ゲームをプレイ",
        "zh": "玩恐龙游戏",
        "el": "Παίξε Dino Game",
        "az": "Dinozavr oyununu oyna",
        "hy": "Դdelays delays",
        "ro": "Joacă Dino Game",
        "cs": "Hrát hru Dino",
        "hi": "डिनो गेम खेलें",
        "bn": "ডিনো গেম খেলুন",
        "ur": "ڈینو گیم کھیلیں",
        "id": "Main game Dino",
        "fa": "بازی داینو"
    },
    "downloads": {
        "en": "Open Downloads",
        "tr": "İndirilenleri Aç",
        "de": "Downloads öffnen",
        "fr": "Ouvrir les téléchargements",
        "it": "Apri download",
        "es": "Abrir descargas",
        "pt": "Abrir downloads",
        "ru": "Открыть загрузки",
        "ja": "ダウンロードを開く",
        "zh": "打开下载",
        "el": "Άνοιγμα λήψεων",
        "az": "Endirmələri aç",
        "hy": "Բdelays delays",
        "ro": "Deschide descărcări",
        "cs": "Otevřít stahování",
        "hi": "डाउनलोड खोलें",
        "bn": "ডাউনলোড খুলুন",
        "ur": "ڈاؤن لوڈز کھولیں",
        "id": "Buka unduhan",
        "fa": "باز کردن دانلودها"
    },
    "extensions": {
        "en": "Manage Extensions",
        "tr": "Eklentileri Yönet",
        "de": "Erweiterungen verwalten",
        "fr": "Gérer les extensions",
        "it": "Gestisci estensioni",
        "es": "Administrar extensiones",
        "pt": "Gerenciar extensões",
        "ru": "Управление расширениями",
        "ja": "拡張機能を管理",
        "zh": "管理扩展程序",
        "el": "Διαχείριση επεκτάσεων",
        "az": "Əlavələri idarə et",
        "hy": " Delays delays",
        "ro": "Gestionează extensii",
        "cs": "Spravovat rozšíření",
        "hi": "एक्सटेंशन प्रबंधित करें",
        "bn": "এক্সটেনশন পরিচালনা করুন",
        "ur": "ایکسٹینشنز کا انتظام کریں",
        "id": "Kelola ekstensi",
        "fa": "مدیریت افزونه‌ها"
    },
    "bookmarks": {
        "en": "Open Bookmarks",
        "tr": "Yer İmlerini Aç",
        "de": "Lesezeichen öffnen",
        "fr": "Ouvrir les favoris",
        "it": "Apri segnalibri",
        "es": "Abrir marcadores",
        "pt": "Abrir favoritos",
        "ru": "Открыть закладки",
        "ja": "ブックマークを開く",
        "zh": "打开书签",
        "el": "Άνοιγμα σελιδοδεικτών",
        "az": "Əlfəcinləri aç",
        "hy": "Բdelays delays",
        "ro": "Deschide marcaje",
        "cs": "Otevřít záložky",
        "hi": "बुकमार्क खोलें",
        "bn": "বুকমার্ক খুলুন",
        "ur": "بک مارکس کھولیں",
        "id": "Buka bookmark",
        "fa": "باز کردن نشانک‌ها"
    },
    "settings": {
        "en": "Browser Settings",
        "tr": "Tarayıcı Ayarları",
        "de": "Browser-Einstellungen",
        "fr": "Paramètres du navigateur",
        "it": "Impostazioni browser",
        "es": "Configuración del navegador",
        "pt": "Configurações do navegador",
        "ru": "Настройки браузера",
        "ja": "ブラウザ設定",
        "zh": "浏览器设置",
        "el": "Ρυθμίσεις προγράμματος περιήγησης",
        "az": "Brauzer parametrləri",
        "hy": "Զdelays delays",
        "ro": "Setări browser",
        "cs": "Nastavení prohlížeče",
        "hi": "ब्राउज़र सेटिंग्स",
        "bn": "ব্রাউজার সেটিংস",
        "ur": "براؤزر سیٹنگز",
        "id": "Pengaturan browser",
        "fa": "تنظیمات مرورگر"
    },
    "search_engine": {
        "en": "Search Engine",
        "tr": "Arama Motoru",
        "de": "Suchmaschine",
        "fr": "Moteur de recherche",
        "it": "Motore di ricerca",
        "es": "Motor de búsqueda",
        "pt": "Motor de busca",
        "ru": "Поисковая система",
        "ja": "検索エンジン",
        "zh": "搜索引擎",
        "el": "Μηχανή αναζήτησης",
        "az": "Axtarış motoru",
        "hy": "Որdelays delays",
        "ro": "Motor de căutare",
        "cs": "Vyhledávač",
        "hi": "खोज इंजन",
        "bn": "সার্চ ইঞ্জিন",
        "ur": "سرچ انجن",
        "id": "Mesin pencari",
        "fa": "موتور جستجو"
    },
    "custom_url": {
        "en": "Custom Search URL",
        "tr": "Özel Arama URL'si",
        "de": "Benutzerdefinierte Such-URL",
        "fr": "URL de recherche personnalisée",
        "it": "URL di ricerca personalizzato",
        "es": "URL de búsqueda personalizada",
        "pt": "URL de pesquisa personalizada",
        "ru": "Пользовательский URL поиска",
        "ja": "カスタム検索URL",
        "zh": "自定义搜索网址",
        "el": "Προσαρμοσμένο URL αναζήτησης",
        "az": "Xüsusi axtarış URL-i",
        "hy": "Հdelays delays URL",
        "ro": "URL de căutare personalizat",
        "cs": "Vlastní URL pro vyhledávání",
        "hi": "कस्टम खोज URL",
        "bn": "কাস্টম অনুসন্ধান URL",
        "ur": "کسٹم سرچ URL",
        "id": "URL pencarian kustom",
        "fa": "URL جستجوی سفارشی"
    },
    "browser_name": {
        "en": "Browser",
        "tr": "Tarayıcı_Adı",
        "de": "Browser",
        "fr": "Navigateur",
        "it": "Browser",
        "es": "Navegador",
        "pt": "Navegador",
        "ru": "Браузер",
        "ja": "ブラウザ",
        "zh": "浏览器",
        "el": "Πρόγραμμα περιήγησης",
        "az": "Brauzer",
        "hy": "Զdelays",
        "ro": "Browser",
        "cs": "Prohlížeč",
        "hi": "ब्राउज़र",
        "bn": "ব্রাউজার",
        "ur": "براؤزر",
        "id": "Browser",
        "fa": "مرورگر"
    }
}
