var data = {
    "en": {
        "search": "Search",
        "search_placeholder": "Search Here",
        "start_searching": "Start searching...",
        "search_dots": "Search...",
        "no_results": "No results found",
        "type_to_search": "Type to start searching",
        "recent_searches": "Recent Searches",
        "clear_history": "Clear History",
        "applications": "Applications",
        "other": "Other",
        "today": "Today",
        "panel_view": "Panel View",
        "results_view": "Results View",
        "button_mode": "Button Mode (Icon only)",
        "medium_mode": "Medium Mode (Button only)",
        "wide_mode": "Wide Mode (Search bar + icon)",
        "extra_wide_mode": "Extra Wide Mode (Wide + Long Placeholder)",
        "list_view": "List View",
        "tile_view": "Tile View",
        "list_icon_size": "List Icon Size",
        "tile_icon_size": "Tile Icon Size",
        "panel_preview": "Panel Preview",
        "results_preview": "Results Preview",
        "application_1": "Application 1",
        "application_2": "Application 2",
        "file_txt": "File.txt",
        "file": "File",
        "category": "Category",
        "path": "Path",
        "general": "General",
        "hint_timeline_today": "Files modified today",
        "hint_timeline_yesterday": "Files modified yesterday",
        "hint_timeline_week": "Files modified this week",
        "hint_timeline_month": "Files modified this month",
        "hint_timeline": "Timeline search",
        "hint_google": "Google search",
        "hint_duckduckgo": "DuckDuckGo search",
        "hint_wikipedia": "Wikipedia search",
        "hint_kill": "Terminate application",
        "hint_spell": "Spell check",
        "hint_unicode": "Unicode character",
        "hint_file_path": "File path",
        "hint_man_page": "Manual page",
        "hint_try": "Try",
        "hint_unknown_prefix": "Unknown prefix",
        "file_size": "Size",
        "modified_date": "Modified",
        "file_type": "Type",
        "open_with": "Open with",
        "preview_shortcut": "Ctrl+Space for preview",
        "profile": "Profile",
        "user_profile": "User Profile",
        "profile_minimal": "Minimal",
        "profile_developer": "Developer",
        "profile_power_user": "Power User",
        "profile_minimal_desc": "Simple interface, basic features",
        "profile_developer_desc": "Debug tab active, developer features",
        "profile_power_desc": "All features active, advanced settings",
        "appearance": "Appearance",
        "search_settings": "Search Settings",
        "enable_preview": "File Preview",
        "preview_description": "Show file info on hover (also triggered by Ctrl+Space)",
        "search_behavior": "Search Behavior",
        "search_info": "Search results provided by Milou/KRunner. Supported prefixes: timeline:, gg:, dd:, kill, spell",
        "debug_settings": "Debug Settings",
        "debug_overlay": "Debug Overlay",
        "debug_overlay_desc": "Show debug info on widget (active mode, item count, index source)",
        "debug_actions": "Debug Actions",
        "dump_debug": "Save Debug Data",
        "dump_debug_desc": "Save debug data to $HOME directory",
        "debug_warning": "This tab only active in Developer mode. Change profile in Appearance tab.",
        "keyboard_shortcuts": "Keyboard Shortcuts",
        "help_navigation": "Navigate between results",
        "help_section_nav": "Switch between sections",
        "help_view_mode": "List / Tile view",
        "help_preview": "Toggle file preview",
        "help_activate": "Open selected item",
        "help_close": "Close widget",
        "search_prefixes": "Search Prefixes",
        "profiles": "Profiles",
        "debug_overlay_title": "DEBUG OVERLAY",
        "backend": "Backend",
        "items": "Items",
        "latency": "Latency",
        "view": "View",
        "display": "Display",
        "total": "TOTAL",
        "avg_lat": "AVG LAT",
        "total_searches": "Total Searches",
        "avg_latency": "Avg Latency",
        "save_dump": "Save Dump",
        "saved": "Saved!",
        "timestamp": "Timestamp",
        "locale": "Locale",
        "display_mode": "Display Mode",
        "view_mode": "View Mode",
        "history_count": "History Count",
        "telemetry": "Telemetry",
        "history_sample": "History Sample",
        "no_history": "No history",
        "telemetry_privacy_notice": "Privacy Notice: All collected debug and telemetry data is stored strictly LOCALLY (~/.config/plasma-org.kde.plasma.desktop-appletsrc). No data is sent over the internet.",
        "debug_data": "Debug Data",
        "prefix": "Prefix",
        "description": "Description",
        "pinned_items": "Pinned Items",
        "pin_item": "Pin",
        "unpin_item": "Unpin",
        "right_click_unpin": "Right-click to unpin",
        "category_settings": "Category Settings",
        "category_settings_desc": "Configure visibility, priority, and icons for each category",
        "category_visibility": "Visibility",
        "category_priority": "Priority",
        "custom_icon": "Custom Icon",
        "select_icon": "Select Icon",
        "priority_tooltip": "Lower number = higher priority",
        "category_info_title": "Category Settings Information",
        "category_info_desc": "Changes are applied immediately. Hidden categories will not appear in search results. Priority determines display order.",
        "files": "Files",
        "documents": "Documents",
        "folders": "Folders",
        "calculator": "Calculator",
        "web": "Web"
    },
    "tr": {
        "search": "Ara",
        "search_placeholder": "Arama Yapın",
        "start_searching": "Arama yapmaya başla...",
        "search_dots": "Arama yap...",
        "no_results": "Sonuç bulunamadı",
        "type_to_search": "Aramak için yazmaya başlayın",
        "recent_searches": "Son Aramalar",
        "clear_history": "Geçmişi Sil",
        "applications": "Uygulamalar",
        "other": "Diğer",
        "today": "Bugün",
        "panel_view": "Panel Görünümü",
        "results_view": "Sonuç Görünümü",
        "button_mode": "Düğme Modu (Sadece ikon)",
        "medium_mode": "Orta Mod (Sadece buton)",
        "wide_mode": "Geniş Mod (Arama çubuğu + ikon)",
        "extra_wide_mode": "Ekstra Geniş Mod (Geniş + Uzun Placeholder)",
        "list_view": "Liste Görünümü",
        "tile_view": "Döşeme Görünümü",
        "list_icon_size": "Liste İkon Boyutu",
        "tile_icon_size": "Döşeme İkon Boyutu",
        "panel_preview": "Panel Önizleme",
        "results_preview": "Sonuç Önizleme",
        "application_1": "Uygulama 1",
        "application_2": "Uygulama 2",
        "file_txt": "Dosya.txt",
        "file": "Dosya",
        "category": "Kategori",
        "path": "Yol",
        "general": "Genel",
        "hint_timeline_today": "Bugün değiştirilen dosyalar",
        "hint_timeline_yesterday": "Dün değiştirilen dosyalar",
        "hint_timeline_week": "Bu hafta değiştirilen dosyalar",
        "hint_timeline_month": "Bu ay değiştirilen dosyalar",
        "hint_timeline": "Zaman çizelgesi araması",
        "hint_google": "Google araması",
        "hint_duckduckgo": "DuckDuckGo araması",
        "hint_wikipedia": "Wikipedia araması",
        "hint_kill": "Uygulamayı sonlandır",
        "hint_spell": "Yazım kontrolü",
        "hint_unicode": "Unicode karakter",
        "hint_file_path": "Dosya yolu",
        "hint_man_page": "Kılavuz sayfası",
        "hint_try": "Deneyin",
        "hint_unknown_prefix": "Bilinmeyen önek",
        "file_size": "Boyut",
        "modified_date": "Değiştirilme",
        "file_type": "Tür",
        "open_with": "Birlikte aç",
        "preview_shortcut": "Önizleme için Ctrl+Space",
        "profile": "Profil",
        "user_profile": "Kullanıcı Profili",
        "profile_minimal": "Minimal",
        "profile_developer": "Geliştirici",
        "profile_power_user": "Güçlü Kullanıcı",
        "profile_minimal_desc": "Basit arayüz, temel özellikler",
        "profile_developer_desc": "Debug sekmesi aktif, geliştirici özellikleri",
        "profile_power_desc": "Tüm özellikler aktif, gelişmiş ayarlar",
        "prefix_timeline": "Bugün değiştirilen dosyaları listeler",
        "prefix_google": "Google üzerinde arama yapar",
        "prefix_ddg": "DuckDuckGo üzerinde arama yapar",
        "prefix_kill": "İşlemleri sonlandırır",
        "prefix_spell": "Yazım denetimi yapar",
        "prefix_unicode": "Unicode karakter kodlarını arar",
        "appearance": "Görünüm",
        "search_settings": "Arama Ayarları",
        "enable_preview": "Dosya Önizlemesi",
        "preview_description": "Hover ile dosya bilgisi göster (Ctrl+Space ile de tetiklenebilir)",
        "search_behavior": "Arama Davranışı",
        "search_info": "Arama sonuçları Milou/KRunner tarafından sağlanmaktadır. Desteklenen prefix'ler: timeline:, gg:, dd:, kill, spell",
        "debug_settings": "Debug Ayarları",
        "debug_overlay": "Debug Overlay",
        "debug_overlay_desc": "Widget üzerinde debug bilgilerini göster (aktif mod, öğe sayısı, index kaynağı)",
        "debug_actions": "Debug İşlemleri",
        "dump_debug": "Debug Verilerini Kaydet",
        "dump_debug_desc": "Debug verilerini $HOME dizinine kaydeder",
        "debug_warning": "Bu sekme sadece Geliştirici modunda aktif olur. Profili Görünüm sekmesinden değiştirin.",
        "keyboard_shortcuts": "Klavye Kısayolları",
        "help_navigation": "Sonuçlar arasında gezin",
        "help_section_nav": "Bölümler arası geçiş",
        "help_view_mode": "Liste / Döşeme görünümü",
        "help_preview": "Dosya önizlemesini aç/kapat",
        "help_activate": "Seçili öğeyi aç",
        "help_close": "Widget'ı kapat",
        "search_prefixes": "Arama Prefix'leri",
        "profiles": "Profiller",
        "debug_overlay_title": "DEBUG OVERLAY",
        "backend": "Arama Motoru",
        "items": "Öğeler",
        "latency": "Gecikme",
        "view": "Görünüm",
        "display": "Ekran",
        "total": "TOPLAM",
        "avg_lat": "ORT GEC",
        "total_searches": "Toplam Arama",
        "avg_latency": "Ortalama Gecikme",
        "save_dump": "Verileri Kaydet",
        "saved": "Kaydedildi!",
        "timestamp": "Zaman Damgası",
        "locale": "Yerel",
        "display_mode": "Ekran Modu",
        "view_mode": "Görünüm Modu",
        "history_count": "Geçmiş Sayısı",
        "telemetry": "Telemetri",
        "history_sample": "Geçmiş Örnekleri",
        "no_history": "Geçmiş boş",
        "telemetry_privacy_notice": "Gizlilik Bildirimi: Toplanan tüm debug ve telemetri verileri SADECE yerel olarak saklanır (~/.config/plasma-org.kde.plasma.desktop-appletsrc). İnternete hiçbir veri gönderilmez.",
        "debug_data": "Debug Verileri",
        "prefix": "Önek",
        "description": "Açıklama",
        "pinned_items": "Sabitlenmiş Öğeler",
        "pin_item": "Sabitle",
        "unpin_item": "Sabitlemeyi Kaldır",
        "right_click_unpin": "Kaldırmak için sağ tıklayın",
        "category_settings": "Kategori Ayarları",
        "category_settings_desc": "Her kategori için görünürlük, öncelik ve ikon ayarlarını yapılandırın",
        "category_visibility": "Görünürlük",
        "category_priority": "Öncelik",
        "custom_icon": "Özel İkon",
        "select_icon": "İkon Seç",
        "priority_tooltip": "Düşük sayı = yüksek öncelik",
        "category_info_title": "Kategori Ayarları Bilgisi",
        "category_info_desc": "Değişiklikler anında uygulanır. Gizlenen kategoriler arama sonuçlarında görünmez. Öncelik, görüntüleme sırasını belirler.",
        "files": "Dosyalar",
        "documents": "Belgeler",
        "folders": "Klasörler",
        "calculator": "Hesap Makinesi",
        "web": "Web"
    },
    "de": {
        "search": "Suche",
        "search_placeholder": "Hier suchen",
        "start_searching": "Suche starten...",
        "search_dots": "Suchen...",
        "no_results": "Keine Ergebnisse gefunden",
        "type_to_search": "Tippen um zu suchen",
        "recent_searches": "Letzte Suchanfragen",
        "clear_history": "Verlauf löschen",
        "applications": "Anwendungen",
        "other": "Andere",
        "today": "Heute",
        "panel_view": "Panelansicht",
        "results_view": "Ergebnisansicht",
        "button_mode": "Tastenmodus (Nur Symbol)",
        "medium_mode": "Mittlerer Modus (Nur Taste)",
        "wide_mode": "Breiter Modus (Suchleiste + Symbol)",
        "extra_wide_mode": "Extra breiter Modus (Breit + Platzhalter)",
        "list_view": "Listenansicht",
        "tile_view": "Kachelansicht",
        "list_icon_size": "Listensymbolgröße",
        "tile_icon_size": "Kachelsymbolgröße",
        "panel_preview": "Panelvorschau",
        "results_preview": "Ergebnisvorschau",
        "application_1": "Anwendung 1",
        "application_2": "Anwendung 2",
        "file_txt": "Datei.txt",
        "file": "Datei",
        "category": "Kategorie",
        "path": "Pfad",
        "general": "Allgemein",
        "profile": "Profil",
        "user_profile": "Benutzerprofil",
        "profile_minimal": "Minimal",
        "profile_developer": "Entwickler",
        "profile_power_user": "Power-Benutzer",
        "profile_minimal_desc": "Einfache Oberfläche, grundlegende Funktionen",
        "profile_developer_desc": "Debug-Tab aktiv, Entwicklerfunktionen",
        "profile_power_desc": "Alle Funktionen aktiv, erweiterte Einstellungen",
        "appearance": "Erscheinungsbild",
        "search_settings": "Sucheinstellungen",
        "enable_preview": "Dateivorschau",
        "debug_overlay": "Debug-Overlay",
        "keyboard_shortcuts": "Tastenkombinationen",
        "search_prefixes": "Suchpräfixe",
        "profiles": "Profile"
    },
    "fr": {
        "search": "Rechercher",
        "search_placeholder": "Rechercher ici",
        "start_searching": "Commencer la recherche...",
        "search_dots": "Rechercher...",
        "no_results": "Aucun résultat trouvé",
        "type_to_search": "Tapez pour rechercher",
        "recent_searches": "Recherches récentes",
        "clear_history": "Effacer l'historique",
        "applications": "Applications",
        "other": "Autre",
        "today": "Aujourd'hui",
        "panel_view": "Vue du panneau",
        "results_view": "Vue des résultats",
        "button_mode": "Mode bouton (Icône seulement)",
        "medium_mode": "Mode moyen (Bouton seulement)",
        "wide_mode": "Mode large (Barre de recherche + icône)",
        "extra_wide_mode": "Mode extra large (Large + Placeholder)",
        "list_view": "Vue en liste",
        "tile_view": "Vue en tuiles",
        "list_icon_size": "Taille des icônes de liste",
        "tile_icon_size": "Taille des icônes de tuile",
        "panel_preview": "Aperçu du panneau",
        "results_preview": "Aperçu des résultats",
        "application_1": "Application 1",
        "application_2": "Application 2",
        "file_txt": "Fichier.txt",
        "file": "Fichier",
        "category": "Catégorie",
        "path": "Chemin",
        "general": "Général",
        "profile": "Profil",
        "user_profile": "Profil utilisateur",
        "profile_minimal": "Minimal",
        "profile_developer": "Développeur",
        "profile_power_user": "Utilisateur avancé",
        "profile_minimal_desc": "Interface simple, fonctionnalités de base",
        "profile_developer_desc": "Onglet débogage actif, fonctionnalités développeur",
        "profile_power_desc": "Toutes les fonctionnalités actives, paramètres avancés",
        "appearance": "Apparence",
        "search_settings": "Paramètres de recherche",
        "enable_preview": "Aperçu des fichiers",
        "debug_overlay": "Overlay de débogage",
        "keyboard_shortcuts": "Raccourcis clavier",
        "search_prefixes": "Préfixes de recherche",
        "profiles": "Profils"
    },
    "ro": {
        "search": "Căutare",
        "search_placeholder": "Caută aici",
        "start_searching": "Începe căutarea...",
        "search_dots": "Caută...",
        "no_results": "Niciun rezultat găsit",
        "type_to_search": "Tastați pentru a căuta",
        "recent_searches": "Căutări recente",
        "clear_history": "Șterge istoricul",
        "applications": "Aplicații",
        "other": "Altele",
        "today": "Astăzi",
        "panel_view": "Vizualizare panou",
        "results_view": "Vizualizare rezultate",
        "button_mode": "Mod buton (Doar pictogramă)",
        "medium_mode": "Mod mediu (Doar buton)",
        "wide_mode": "Mod lat (Bară de căutare + pictogramă)",
        "extra_wide_mode": "Mod extra lat (Lat + Substituent)",
        "list_view": "Vizualizare listă",
        "tile_view": "Vizualizare dale",
        "list_icon_size": "Dimensiune pictograme listă",
        "tile_icon_size": "Dimensiune pictograme dale",
        "panel_preview": "Previzualizare panou",
        "results_preview": "Previzualizare rezultate",
        "application_1": "Aplicația 1",
        "application_2": "Aplicația 2",
        "file_txt": "Fișier.txt",
        "file": "Fișier",
        "category": "Categorie",
        "path": "Cale",
        "general": "General",
        "profile": "Profil",
        "user_profile": "Profil utilizator",
        "profile_minimal": "Minimal",
        "profile_developer": "Dezvoltator",
        "profile_power_user": "Utilizator avansat",
        "appearance": "Aspect",
        "keyboard_shortcuts": "Comenzi rapide",
        "profiles": "Profiluri"
    },
    "cs": {
        "search": "Hledat",
        "search_placeholder": "Hledat zde",
        "start_searching": "Začít hledat...",
        "search_dots": "Hledat...",
        "no_results": "Žádné výsledky",
        "type_to_search": "Pište pro hledání",
        "recent_searches": "Nedávná hledání",
        "clear_history": "Vymazat historii",
        "applications": "Aplikace",
        "other": "Jiné",
        "today": "Dnes",
        "panel_view": "Zobrazení panelu",
        "results_view": "Zobrazení výsledků",
        "button_mode": "Režim tlačítka (Pouze ikona)",
        "medium_mode": "Střední režim (Pouze tlačítko)",
        "wide_mode": "Široký režim (Vyhledávací panel + ikona)",
        "extra_wide_mode": "Extra široký režim (Široký + Zástupný text)",
        "list_view": "Zobrazení seznamu",
        "tile_view": "Zobrazení dlaždic",
        "list_icon_size": "Velikost ikon seznamu",
        "tile_icon_size": "Velikost ikon dlaždic",
        "panel_preview": "Náhled panelu",
        "results_preview": "Náhled výsledků",
        "application_1": "Aplikace 1",
        "application_2": "Aplikace 2",
        "file_txt": "Soubor.txt",
        "file": "Soubor",
        "category": "Kategorie",
        "path": "Cesta",
        "general": "Obecné",
        "profile": "Profil",
        "profile_minimal": "Minimální",
        "profile_developer": "Vývojář",
        "appearance": "Vzhled",
        "keyboard_shortcuts": "Klávesové zkratky"
    },
    "es": {
        "search": "Buscar",
        "search_placeholder": "Buscar aquí",
        "start_searching": "Empezar a buscar...",
        "search_dots": "Buscar...",
        "no_results": "No se encontraron resultados",
        "type_to_search": "Escriba para buscar",
        "recent_searches": "Búsquedas recientes",
        "clear_history": "Borrar historial",
        "applications": "Aplicaciones",
        "other": "Otros",
        "today": "Hoy",
        "panel_view": "Vista del panel",
        "results_view": "Vista de resultados",
        "button_mode": "Modo botón (Solo icono)",
        "medium_mode": "Modo medio (Solo botón)",
        "wide_mode": "Modo ancho (Barra de búsqueda + icono)",
        "extra_wide_mode": "Modo extra ancho (Ancho + Marcador de posición)",
        "list_view": "Vista de lista",
        "tile_view": "Vista de mosaico",
        "list_icon_size": "Tamaño de iconos de lista",
        "tile_icon_size": "Tamaño de iconos de mosaico",
        "panel_preview": "Previsualización del panel",
        "results_preview": "Previsualización de resultados",
        "application_1": "Aplicación 1",
        "application_2": "Aplicación 2",
        "file_txt": "Archivo.txt",
        "file": "Archivo",
        "category": "Categoría",
        "path": "Ruta",
        "general": "General",
        "profile": "Perfil",
        "profile_minimal": "Mínimo",
        "profile_developer": "Desarrollador",
        "appearance": "Apariencia",
        "keyboard_shortcuts": "Atajos de teclado"
    },
    "ru": {
        "search": "Поиск",
        "search_placeholder": "Искать здесь",
        "start_searching": "Начать поиск...",
        "search_dots": "Поиск...",
        "no_results": "Результатов не найдено",
        "type_to_search": "Введите для поиска",
        "recent_searches": "Недавние поиски",
        "clear_history": "Очистить историю",
        "applications": "Приложения",
        "other": "Другое",
        "today": "Сегодня",
        "panel_view": "Вид панели",
        "results_view": "Вид результатов",
        "button_mode": "Режим кнопки (Только иконка)",
        "medium_mode": "Средний режим (Только кнопка)",
        "wide_mode": "Широкий режим (Строка поиска + иконка)",
        "extra_wide_mode": "Экстра широкий режим (Широкий + Заполнитель)",
        "list_view": "Вид списка",
        "tile_view": "Вид плитки",
        "list_icon_size": "Размер иконок списка",
        "tile_icon_size": "Размер иконок плитки",
        "panel_preview": "Предпросмотр панели",
        "results_preview": "Предпросмотр результатов",
        "application_1": "Приложение 1",
        "application_2": "Приложение 2",
        "file_txt": "Файл.txt",
        "file": "Файл",
        "category": "Категория",
        "path": "Путь",
        "general": "Общее",
        "profile": "Профиль",
        "profile_minimal": "Минимальный",
        "profile_developer": "Разработчик",
        "appearance": "Внешний вид",
        "keyboard_shortcuts": "Горячие клавиши"
    },
    "pt": {
        "search": "Pesquisar",
        "search_placeholder": "Pesquisar aqui",
        "start_searching": "Começar a pesquisar...",
        "search_dots": "Pesquisar...",
        "no_results": "Nenhum resultado encontrado",
        "type_to_search": "Digite para pesquisar",
        "recent_searches": "Pesquisas recentes",
        "clear_history": "Limpar histórico",
        "applications": "Aplicações",
        "other": "Outros",
        "today": "Hoje",
        "panel_view": "Visualização do painel",
        "results_view": "Visualização de resultados",
        "button_mode": "Modo botão (Apenas ícone)",
        "medium_mode": "Modo médio (Apenas botão)",
        "wide_mode": "Modo amplo (Barra de pesquisa + ícone)",
        "extra_wide_mode": "Modo extra amplo (Amplo + Espaço reservado)",
        "list_view": "Visualização em lista",
        "tile_view": "Visualização em blocos",
        "list_icon_size": "Tamanho do ícone da lista",
        "tile_icon_size": "Tamanho do ícone do bloco",
        "panel_preview": "Pré-visualização do painel",
        "results_preview": "Pré-visualização de resultados",
        "application_1": "Aplicação 1",
        "application_2": "Aplicação 2",
        "file_txt": "Arquivo.txt",
        "file": "Arquivo",
        "category": "Categoria",
        "path": "Caminho",
        "general": "Geral",
        "profile": "Perfil",
        "profile_minimal": "Mínimo",
        "profile_developer": "Desenvolvedor",
        "appearance": "Aparência",
        "keyboard_shortcuts": "Atalhos de teclado"
    },
    "ja": {
        "search": "検索",
        "search_placeholder": "ここで検索",
        "start_searching": "検索を開始...",
        "search_dots": "検索...",
        "no_results": "結果が見つかりません",
        "type_to_search": "入力して検索を開始",
        "recent_searches": "最近の検索",
        "clear_history": "履歴を消去",
        "applications": "アプリケーション",
        "other": "その他",
        "today": "今日",
        "panel_view": "パネル表示",
        "results_view": "結果表示",
        "button_mode": "ボタンモード (アイコンのみ)",
        "medium_mode": "中モード (ボタンのみ)",
        "wide_mode": "ワイドモード (検索バー + アイコン)",
        "extra_wide_mode": "エクストラワイドモード (ワイド + プレースホルダー)",
        "list_view": "リスト表示",
        "tile_view": "タイル表示",
        "list_icon_size": "リストアイコンサイズ",
        "tile_icon_size": "タイルアイコンサイズ",
        "panel_preview": "パネルプレビュー",
        "results_preview": "結果プレビュー",
        "application_1": "アプリケーション 1",
        "application_2": "アプリケーション 2",
        "file_txt": "ファイル.txt",
        "file": "ファイル",
        "category": "カテゴリ",
        "path": "パス",
        "general": "一般",
        "profile": "プロファイル",
        "profile_minimal": "ミニマル",
        "profile_developer": "開発者",
        "appearance": "外観",
        "keyboard_shortcuts": "キーボードショートカット"
    }
}