var data = {
    "en": {
        "search": "Search",
        "search_placeholder": "Search Here",
        "start_searching": "Start searching...",
        "search_dots": "Search...",
        "no_results": "No results found",
        "type_to_search": "Type to start searching",
        "recent_searches": "Recent Searches",
        "clear_history": "Clear History",
        "applications": "Applications",
        "other": "Other",
        "today": "Today",
        "panel_view": "Panel View",
        "results_view": "Results View",
        "button_mode": "Button Mode (Icon only)",
        "medium_mode": "Medium Mode (Button only)",
        "wide_mode": "Wide Mode (Search bar + icon)",
        "extra_wide_mode": "Extra Wide Mode (Wide + Long Placeholder)",
        "list_view": "List View",
        "tile_view": "Tile View",
        "list_icon_size": "List Icon Size",
        "tile_icon_size": "Tile Icon Size",
        "panel_preview": "Panel Preview",
        "results_preview": "Results Preview",
        "application_1": "Application 1",
        "application_2": "Application 2",
        "file_txt": "File.txt",
        "file": "File",
        "category": "Category",
        "path": "Path",
        "general": "General",
        "hint_timeline_today": "Files modified today",
        "hint_timeline_yesterday": "Files modified yesterday",
        "hint_timeline_week": "Files modified this week",
        "hint_timeline_month": "Files modified this month",
        "hint_timeline": "Timeline search",
        "hint_google": "Google search",
        "hint_duckduckgo": "DuckDuckGo search",
        "hint_wikipedia": "Wikipedia search",
        "hint_kill": "Terminate application",
        "hint_spell": "Spell check",
        "hint_unicode": "Unicode character",
        "hint_file_path": "File path",
        "hint_man_page": "Manual page",
        "hint_try": "Try",
        "hint_unknown_prefix": "Unknown prefix",
        "file_size": "Size",
        "modified_date": "Modified",
        "file_type": "Type",
        "open_with": "Open with",
        "preview_shortcut": "Ctrl+Space for preview",
        "profile": "Profile",
        "user_profile": "User Profile",
        "profile_minimal": "Minimal",
        "profile_developer": "Developer",
        "profile_power_user": "Power User",
        "profile_minimal_desc": "Simple interface, basic features",
        "profile_developer_desc": "Debug tab active, developer features",
        "profile_power_desc": "All features active, advanced settings",
        "appearance": "Appearance",
        "search_settings": "Search Settings",
        "enable_preview": "File Preview",
        "preview_description": "Show file info on hover (also triggered by Ctrl+Space)",
        "search_behavior": "Search Behavior",
        "search_info": "Search results provided by Milou/KRunner. Supported prefixes: timeline:, gg:, dd:, kill, spell",
        "debug_settings": "Debug Settings",
        "debug_overlay": "Debug Overlay",
        "debug_overlay_desc": "Show debug info on widget (active mode, item count, index source)",
        "debug_actions": "Debug Actions",
        "dump_debug": "Save Debug Data",
        "dump_debug_desc": "Save debug data to $HOME directory",
        "debug_warning": "This tab only active in Developer mode. Change profile in Appearance tab.",
        "keyboard_shortcuts": "Keyboard Shortcuts",
        "help_navigation": "Navigate between results",
        "help_section_nav": "Switch between sections",
        "help_view_mode": "List / Tile view",
        "help_preview": "Toggle file preview",
        "help_activate": "Open selected item",
        "help_close": "Close widget",
        "search_prefixes": "Search Prefixes",
        "profiles": "Profiles",
        "debug_overlay_title": "DEBUG OVERLAY",
        "backend": "Backend",
        "items": "Items",
        "latency": "Latency",
        "view": "View",
        "display": "Display",
        "total": "TOTAL",
        "avg_lat": "AVG LAT",
        "total_searches": "Total Searches",
        "avg_latency": "Avg Latency",
        "save_dump": "Save Dump",
        "saved": "Saved!",
        "timestamp": "Timestamp",
        "locale": "Locale",
        "display_mode": "Display Mode",
        "view_mode": "View Mode",
        "history_count": "History Count",
        "telemetry": "Telemetry",
        "history_sample": "History Sample",
        "no_history": "No history",
        "telemetry_privacy_notice": "Privacy Notice: All collected debug and telemetry data is stored strictly LOCALLY (~/.config/plasma-org.kde.plasma.desktop-appletsrc). No data is sent over the internet.",
        "debug_data": "Debug Data",
        "prefix": "Prefix",
        "description": "Description",
        "pinned_items": "Pinned Items",
        "pin_item": "Pin",
        "unpin_item": "Unpin",
        "right_click_unpin": "Right-click to unpin",
        "category_settings": "Category Settings",
        "category_settings_desc": "Configure visibility, priority, and icons for each category",
        "category_visibility": "Visibility",
        "category_priority": "Priority",
        "custom_icon": "Custom Icon",
        "select_icon": "Select Icon",
        "priority_tooltip": "Lower number = higher priority",
        "category_info_title": "Category Settings Information",
        "category_info_desc": "Changes are applied immediately. Hidden categories will not appear in search results. Priority determines display order.",
        "files": "Files",
        "documents": "Documents",
        "folders": "Folders",
        "calculator": "Calculator",
        "web": "Web",
        "open": "Open",
        "copy_path": "Copy Path",
        "open_in_terminal": "Open in Terminal",
        "move_to_trash": "Move to Trash",
        "open_location": "Open Containing Folder",
        "show_properties": "Properties",
        "manage_app": "Manage Application",
        "remove_from_history": "Remove from History",
        "reset_stats": "Reset Statistics",
        "hint_applications": "Applications",
        "hint_shell": "Run Command",
        "hint_bookmarks": "Bookmarks",
        "hint_power": "Power Management",
        "hint_services": "System Settings",
        "hint_datetime": "Date & Time",
        "hint_define": "Dictionary Definition",
        "hint_unit": "Unit Converter",
        "hint_help": "Help & Shortcuts",
        "man_not_installed": "Man package is not installed"
    },
    "tr": {
        "search": "Ara",
        "search_placeholder": "Arama Yapın",
        "start_searching": "Arama yapmaya başla...",
        "search_dots": "Arama yap...",
        "no_results": "Sonuç bulunamadı",
        "type_to_search": "Aramak için yazmaya başlayın",
        "recent_searches": "Son Aramalar",
        "clear_history": "Geçmişi Sil",
        "applications": "Uygulamalar",
        "other": "Diğer",
        "today": "Bugün",
        "panel_view": "Panel Görünümü",
        "results_view": "Sonuç Görünümü",
        "button_mode": "Düğme Modu (Sadece ikon)",
        "medium_mode": "Orta Mod (Sadece buton)",
        "wide_mode": "Geniş Mod (Arama çubuğu + ikon)",
        "extra_wide_mode": "Ekstra Geniş Mod (Geniş + Uzun Placeholder)",
        "list_view": "Liste Görünümü",
        "tile_view": "Döşeme Görünümü",
        "list_icon_size": "Liste İkon Boyutu",
        "tile_icon_size": "Döşeme İkon Boyutu",
        "panel_preview": "Panel Önizleme",
        "results_preview": "Sonuç Önizleme",
        "application_1": "Uygulama 1",
        "application_2": "Uygulama 2",
        "file_txt": "Dosya.txt",
        "file": "Dosya",
        "category": "Kategori",
        "path": "Yol",
        "general": "Genel",
        "hint_timeline_today": "Bugün değiştirilen dosyalar",
        "hint_timeline_yesterday": "Dün değiştirilen dosyalar",
        "hint_timeline_week": "Bu hafta değiştirilen dosyalar",
        "hint_timeline_month": "Bu ay değiştirilen dosyalar",
        "hint_timeline": "Zaman çizelgesi araması",
        "hint_google": "Google araması",
        "hint_duckduckgo": "DuckDuckGo araması",
        "hint_wikipedia": "Wikipedia araması",
        "hint_kill": "Uygulamayı sonlandır",
        "hint_spell": "Yazım kontrolü",
        "hint_unicode": "Unicode karakter",
        "hint_file_path": "Dosya yolu",
        "hint_man_page": "Kılavuz sayfası",
        "hint_try": "Deneyin",
        "hint_unknown_prefix": "Bilinmeyen önek",
        "hint_applications": "Uygulamalar",
        "hint_shell": "Komut Çalıştır",
        "hint_bookmarks": "Yer İmleri",
        "hint_power": "Güç Yönetimi",
        "hint_services": "Sistem Ayarları",
        "hint_datetime": "Tarih ve Saat",
        "hint_define": "Sözlük Tanımı",
        "hint_unit": "Birim Çevirici",
        "hint_help": "Yardım ve Kısayollar",
        "man_not_installed": "Man paketi yüklü değil",
        "file_size": "Boyut",
        "modified_date": "Değiştirilme",
        "file_type": "Tür",
        "open_with": "Birlikte aç",
        "preview_shortcut": "Önizleme için Ctrl+Space",
        "profile": "Profil",
        "user_profile": "Kullanıcı Profili",
        "profile_minimal": "Minimal",
        "profile_developer": "Geliştirici",
        "profile_power_user": "Güçlü Kullanıcı",
        "profile_minimal_desc": "Basit arayüz, temel özellikler",
        "profile_developer_desc": "Debug sekmesi aktif, geliştirici özellikleri",
        "profile_power_desc": "Tüm özellikler aktif, gelişmiş ayarlar",
        "prefix_timeline": "Bugün değiştirilen dosyaları listeler",
        "prefix_google": "Google üzerinde arama yapar",
        "prefix_ddg": "DuckDuckGo üzerinde arama yapar",
        "prefix_kill": "İşlemleri sonlandırır",
        "prefix_spell": "Yazım denetimi yapar",
        "prefix_unicode": "Unicode karakter kodlarını arar",
        "appearance": "Görünüm",
        "search_settings": "Arama Ayarları",
        "enable_preview": "Dosya Önizlemesi",
        "preview_description": "Hover ile dosya bilgisi göster (Ctrl+Space ile de tetiklenebilir)",
        "search_behavior": "Arama Davranışı",
        "search_info": "Arama sonuçları Milou/KRunner tarafından sağlanmaktadır. Desteklenen prefix'ler: timeline:, gg:, dd:, kill, spell",
        "debug_settings": "Debug Ayarları",
        "debug_overlay": "Debug Overlay",
        "debug_overlay_desc": "Widget üzerinde debug bilgilerini göster (aktif mod, öğe sayısı, index kaynağı)",
        "debug_actions": "Debug İşlemleri",
        "dump_debug": "Debug Verilerini Kaydet",
        "dump_debug_desc": "Debug verilerini $HOME dizinine kaydeder",
        "debug_warning": "Bu sekme sadece Geliştirici modunda aktif olur. Profili Görünüm sekmesinden değiştirin.",
        "keyboard_shortcuts": "Klavye Kısayolları",
        "help_navigation": "Sonuçlar arasında gezin",
        "help_section_nav": "Bölümler arası geçiş",
        "help_view_mode": "Liste / Döşeme görünümü",
        "help_preview": "Dosya önizlemesini aç/kapat",
        "help_activate": "Seçili öğeyi aç",
        "help_close": "Widget'ı kapat",
        "search_prefixes": "Arama Prefix'leri",
        "profiles": "Profiller",
        "debug_overlay_title": "DEBUG OVERLAY",
        "backend": "Arama Motoru",
        "items": "Öğeler",
        "latency": "Gecikme",
        "view": "Görünüm",
        "display": "Ekran",
        "total": "TOPLAM",
        "avg_lat": "ORT GEC",
        "total_searches": "Toplam Arama",
        "avg_latency": "Ortalama Gecikme",
        "save_dump": "Verileri Kaydet",
        "saved": "Kaydedildi!",
        "timestamp": "Zaman Damgası",
        "locale": "Yerel",
        "display_mode": "Ekran Modu",
        "view_mode": "Görünüm Modu",
        "history_count": "Geçmiş Sayısı",
        "telemetry": "Telemetri",
        "history_sample": "Geçmiş Örnekleri",
        "no_history": "Geçmiş boş",
        "telemetry_privacy_notice": "Gizlilik Bildirimi: Toplanan tüm debug ve telemetri verileri SADECE yerel olarak saklanır (~/.config/plasma-org.kde.plasma.desktop-appletsrc). İnternete hiçbir veri gönderilmez.",
        "debug_data": "Debug Verileri",
        "prefix": "Önek",
        "description": "Açıklama",
        "pinned_items": "Sabitlenmiş Öğeler",
        "pin_item": "Sabitle",
        "unpin_item": "Sabitlemeyi Kaldır",
        "right_click_unpin": "Kaldırmak için sağ tıklayın",
        "category_settings": "Kategori Ayarları",
        "category_settings_desc": "Her kategori için görünürlük, öncelik ve ikon ayarlarını yapılandırın",
        "category_visibility": "Görünürlük",
        "category_priority": "Öncelik",
        "custom_icon": "Özel İkon",
        "select_icon": "İkon Seç",
        "priority_tooltip": "Düşük sayı = yüksek öncelik",
        "category_info_title": "Kategori Ayarları Bilgisi",
        "category_info_desc": "Değişiklikler anında uygulanır. Gizlenen kategoriler arama sonuçlarında görünmez. Öncelik, görüntüleme sırasını belirler.",
        "files": "Dosyalar",
        "documents": "Belgeler",
        "folders": "Klasörler",
        "calculator": "Hesap Makinesi",
        "web": "Web",
        "open": "Aç",
        "copy_path": "Yolu Kopyala",
        "open_in_terminal": "Terminalde Aç",
        "move_to_trash": "Çöp Kutusuna Taşı",
        "open_location": "Bulunduğu Klasörü Aç",
        "show_properties": "Özellikler",
        "manage_app": "Uygulamayı Yönet",
        "remove_from_history": "Geçmişten Kaldır",
        "reset_stats": "İstatistikleri Sıfırla"
    },
    "de": {
        "search": "Suche",
        "search_placeholder": "Hier suchen",
        "start_searching": "Suche starten...",
        "search_dots": "Suchen...",
        "no_results": "Keine Ergebnisse gefunden",
        "type_to_search": "Tippen um zu suchen",
        "recent_searches": "Letzte Suchanfragen",
        "clear_history": "Verlauf löschen",
        "applications": "Anwendungen",
        "other": "Andere",
        "today": "Heute",
        "panel_view": "Panelansicht",
        "results_view": "Ergebnisansicht",
        "button_mode": "Tastenmodus (Nur Symbol)",
        "medium_mode": "Mittlerer Modus (Nur Taste)",
        "wide_mode": "Breiter Modus (Suchleiste + Symbol)",
        "extra_wide_mode": "Extra breiter Modus (Breit + Platzhalter)",
        "list_view": "Listenansicht",
        "tile_view": "Kachelansicht",
        "list_icon_size": "Listensymbolgröße",
        "tile_icon_size": "Kachelsymbolgröße",
        "panel_preview": "Panelvorschau",
        "results_preview": "Ergebnisvorschau",
        "application_1": "Anwendung 1",
        "application_2": "Anwendung 2",
        "file_txt": "Datei.txt",
        "file": "Datei",
        "category": "Kategorie",
        "path": "Pfad",
        "general": "Allgemein",
        "profile": "Profil",
        "user_profile": "Benutzerprofil",
        "profile_minimal": "Minimal",
        "profile_developer": "Entwickler",
        "profile_power_user": "Power-Benutzer",
        "profile_minimal_desc": "Einfache Oberfläche, grundlegende Funktionen",
        "profile_developer_desc": "Debug-Tab aktiv, Entwicklerfunktionen",
        "profile_power_desc": "Alle Funktionen aktiv, erweiterte Einstellungen",
        "appearance": "Erscheinungsbild",
        "search_settings": "Sucheinstellungen",
        "enable_preview": "Dateivorschau",
        "debug_overlay": "Debug-Overlay",
        "keyboard_shortcuts": "Tastenkombinationen",
        "search_prefixes": "Suchpräfixe",
        "profiles": "Profile",
        "open": "Öffnen",
        "copy_path": "Pfad kopieren",
        "open_in_terminal": "Im Terminal öffnen",
        "move_to_trash": "In den Papierkorb verschieben",
        "open_location": "Übergeordneten Ordner öffnen",
        "show_properties": "Eigenschaften",
        "manage_app": "Anwendung verwalten",
        "remove_from_history": "Aus Verlauf entfernen",
        "reset_stats": "Statistiken zurücksetzen",
        "hint_applications": "Anwendungen",
        "hint_shell": "Befehl ausführen",
        "hint_bookmarks": "Lesezeichen",
        "hint_power": "Energieverwaltung",
        "hint_services": "Systemeinstellungen",
        "hint_datetime": "Datum & Zeit",
        "hint_define": "Wörterbuchdefinition",
        "hint_unit": "Einheitenumrechner",
        "hint_help": "Hilfe & Kurzbefehle",
        "man_not_installed": "Man-Paket ist nicht installiert"
    },
    "fr": {
        "search": "Rechercher",
        "search_placeholder": "Rechercher ici",
        "start_searching": "Commencer la recherche...",
        "search_dots": "Rechercher...",
        "no_results": "Aucun résultat trouvé",
        "type_to_search": "Tapez pour rechercher",
        "recent_searches": "Recherches récentes",
        "clear_history": "Effacer l'historique",
        "applications": "Applications",
        "other": "Autre",
        "today": "Aujourd'hui",
        "panel_view": "Vue du panneau",
        "results_view": "Vue des résultats",
        "button_mode": "Mode bouton (Icône seulement)",
        "medium_mode": "Mode moyen (Bouton seulement)",
        "wide_mode": "Mode large (Barre de recherche + icône)",
        "extra_wide_mode": "Mode extra large (Large + Placeholder)",
        "list_view": "Vue en liste",
        "tile_view": "Vue en tuiles",
        "list_icon_size": "Taille des icônes de liste",
        "tile_icon_size": "Taille des icônes de tuile",
        "panel_preview": "Aperçu du panneau",
        "results_preview": "Aperçu des résultats",
        "application_1": "Application 1",
        "application_2": "Application 2",
        "file_txt": "Fichier.txt",
        "file": "Fichier",
        "category": "Catégorie",
        "path": "Chemin",
        "general": "Général",
        "profile": "Profil",
        "user_profile": "Profil utilisateur",
        "profile_minimal": "Minimal",
        "profile_developer": "Développeur",
        "profile_power_user": "Utilisateur avancé",
        "profile_minimal_desc": "Interface simple, fonctionnalités de base",
        "profile_developer_desc": "Onglet débogage actif, fonctionnalités développeur",
        "profile_power_desc": "Toutes les fonctionnalités actives, paramètres avancés",
        "appearance": "Apparence",
        "search_settings": "Paramètres de recherche",
        "enable_preview": "Aperçu des fichiers",
        "debug_overlay": "Overlay de débogage",
        "keyboard_shortcuts": "Raccourcis clavier",
        "search_prefixes": "Préfixes de recherche",
        "profiles": "Profils",
        "open": "Ouvrir",
        "copy_path": "Copier le chemin",
        "open_in_terminal": "Ouvrir dans le terminal",
        "move_to_trash": "Mettre à la corbeille",
        "open_location": "Ouvrir le dossier contenant",
        "show_properties": "Propriétés",
        "manage_app": "Gérer l'application",
        "remove_from_history": "Supprimer de l'historique",
        "reset_stats": "Réinitialiser les statistiques",
        "hint_applications": "Applications",
        "hint_shell": "Exécuter une commande",
        "hint_bookmarks": "Signets",
        "hint_power": "Gestion de l'énergie",
        "hint_services": "Paramètres système",
        "hint_datetime": "Date et heure",
        "hint_define": "Définition du dictionnaire",
        "hint_unit": "Convertisseur d'unités",
        "hint_help": "Aide et raccourcis",
        "man_not_installed": "Le paquet Man n'est pas installé"
    },
    "ro": {
        "search": "Căutare",
        "search_placeholder": "Caută aici",
        "start_searching": "Începe căutarea...",
        "search_dots": "Caută...",
        "no_results": "Niciun rezultat găsit",
        "type_to_search": "Tastați pentru a căuta",
        "recent_searches": "Căutări recente",
        "clear_history": "Șterge istoricul",
        "applications": "Aplicații",
        "other": "Altele",
        "today": "Astăzi",
        "panel_view": "Vizualizare panou",
        "results_view": "Vizualizare rezultate",
        "button_mode": "Mod buton (Doar pictogramă)",
        "medium_mode": "Mod mediu (Doar buton)",
        "wide_mode": "Mod lat (Bară de căutare + pictogramă)",
        "extra_wide_mode": "Mod extra lat (Lat + Substituent)",
        "list_view": "Vizualizare listă",
        "tile_view": "Vizualizare dale",
        "list_icon_size": "Dimensiune pictograme listă",
        "tile_icon_size": "Dimensiune pictograme dale",
        "panel_preview": "Previzualizare panou",
        "results_preview": "Previzualizare rezultate",
        "application_1": "Aplicația 1",
        "application_2": "Aplicația 2",
        "file_txt": "Fișier.txt",
        "file": "Fișier",
        "category": "Categorie",
        "path": "Cale",
        "general": "General",
        "profile": "Profil",
        "user_profile": "Profil utilizator",
        "profile_minimal": "Minimal",
        "profile_developer": "Dezvoltator",
        "profile_power_user": "Utilizator avansat",
        "appearance": "Aspect",
        "keyboard_shortcuts": "Comenzi rapide",
        "profiles": "Profiluri",
        "open": "Deschide",
        "copy_path": "Copiază calea",
        "open_in_terminal": "Deschide în terminal",
        "move_to_trash": "Mută la coșul de gunoi",
        "open_location": "Deschide dosarul conținător",
        "show_properties": "Proprietăți",
        "manage_app": "Gestionează aplicația",
        "remove_from_history": "Elimină din istoric",
        "reset_stats": "Resetează statisticile",
        "hint_applications": "Aplicații",
        "hint_shell": "Execută comandă",
        "hint_bookmarks": "Marcaje",
        "hint_power": "Gestionare energie",
        "hint_services": "Setări sistem",
        "hint_datetime": "Dată și oră",
        "hint_define": "Definiție dicționar",
        "hint_unit": "Convertor unități",
        "hint_help": "Ajutor și scurtături",
        "man_not_installed": "Pachetul Man nu este instalat"
    },
    "cs": {
        "search": "Hledat",
        "search_placeholder": "Hledat zde",
        "start_searching": "Začít hledat...",
        "search_dots": "Hledat...",
        "no_results": "Žádné výsledky",
        "type_to_search": "Pište pro hledání",
        "recent_searches": "Nedávná hledání",
        "clear_history": "Vymazat historii",
        "applications": "Aplikace",
        "other": "Jiné",
        "today": "Dnes",
        "panel_view": "Zobrazení panelu",
        "results_view": "Zobrazení výsledků",
        "button_mode": "Režim tlačítka (Pouze ikona)",
        "medium_mode": "Střední režim (Pouze tlačítko)",
        "wide_mode": "Široký režim (Vyhledávací panel + ikona)",
        "extra_wide_mode": "Extra široký režim (Široký + Zástupný text)",
        "list_view": "Zobrazení seznamu",
        "tile_view": "Zobrazení dlaždic",
        "list_icon_size": "Velikost ikon seznamu",
        "tile_icon_size": "Velikost ikon dlaždic",
        "panel_preview": "Náhled panelu",
        "results_preview": "Náhled výsledků",
        "application_1": "Aplikace 1",
        "application_2": "Aplikace 2",
        "file_txt": "Soubor.txt",
        "file": "Soubor",
        "category": "Kategorie",
        "path": "Cesta",
        "general": "Obecné",
        "profile": "Profil",
        "profile_minimal": "Minimální",
        "profile_developer": "Vývojář",
        "appearance": "Vzhled",
        "keyboard_shortcuts": "Klávesové zkratky",
        "open": "Otevřít",
        "copy_path": "Kopírovat cestu",
        "open_in_terminal": "Otevřít v terminálu",
        "move_to_trash": "Přesunout do koše",
        "open_location": "Otevřít složku",
        "show_properties": "Vlastnosti",
        "manage_app": "Spravovat aplikaci",
        "remove_from_history": "Odstranit z historie",
        "reset_stats": "Resetovat statistiky",
        "hint_applications": "Aplikace",
        "hint_shell": "Spustit příkaz",
        "hint_bookmarks": "Záložky",
        "hint_power": "Správa napájení",
        "hint_services": "Nastavení systému",
        "hint_datetime": "Datum a čas",
        "hint_define": "Definice ve slovníku",
        "hint_unit": "Převodník jednotek",
        "hint_help": "Nápověda a zkratky",
        "man_not_installed": "Balíček Man není nainstalován"
    },
    "es": {
        "search": "Buscar",
        "search_placeholder": "Buscar aquí",
        "start_searching": "Empezar a buscar...",
        "search_dots": "Buscar...",
        "no_results": "No se encontraron resultados",
        "type_to_search": "Escriba para buscar",
        "recent_searches": "Búsquedas recientes",
        "clear_history": "Borrar historial",
        "applications": "Aplicaciones",
        "other": "Otros",
        "today": "Hoy",
        "panel_view": "Vista del panel",
        "results_view": "Vista de resultados",
        "button_mode": "Modo botón (Solo icono)",
        "medium_mode": "Modo medio (Solo botón)",
        "wide_mode": "Modo ancho (Barra de búsqueda + icono)",
        "extra_wide_mode": "Modo extra ancho (Ancho + Marcador de posición)",
        "list_view": "Vista de lista",
        "tile_view": "Vista de mosaico",
        "list_icon_size": "Tamaño de iconos de lista",
        "tile_icon_size": "Tamaño de iconos de mosaico",
        "panel_preview": "Previsualización del panel",
        "results_preview": "Previsualización de resultados",
        "application_1": "Aplicación 1",
        "application_2": "Aplicación 2",
        "file_txt": "Archivo.txt",
        "file": "Archivo",
        "category": "Categoría",
        "path": "Ruta",
        "general": "General",
        "profile": "Perfil",
        "profile_minimal": "Mínimo",
        "profile_developer": "Desarrollador",
        "appearance": "Apariencia",
        "keyboard_shortcuts": "Atajos de teclado",
        "open": "Abrir",
        "copy_path": "Copiar ruta",
        "open_in_terminal": "Abrir en terminal",
        "move_to_trash": "Mover a la papelera",
        "open_location": "Abrir carpeta contenedora",
        "show_properties": "Propiedades",
        "manage_app": "Gestionar aplicación",
        "remove_from_history": "Eliminar del historial",
        "reset_stats": "Restablecer estadísticas",
        "hint_applications": "Aplicaciones",
        "hint_shell": "Ejecutar comando",
        "hint_bookmarks": "Marcadores",
        "hint_power": "Gestión de energía",
        "hint_services": "Configuración del sistema",
        "hint_datetime": "Fecha y hora",
        "hint_define": "Definición de diccionario",
        "hint_unit": "Conversor de unidades",
        "hint_help": "Ayuda y atajos",
        "man_not_installed": "El paquete Man no está instalado"
    },
    "ru": {
        "search": "Поиск",
        "search_placeholder": "Искать здесь",
        "start_searching": "Начать поиск...",
        "search_dots": "Поиск...",
        "no_results": "Результатов не найдено",
        "type_to_search": "Введите для поиска",
        "recent_searches": "Недавние поиски",
        "clear_history": "Очистить историю",
        "applications": "Приложения",
        "other": "Другое",
        "today": "Сегодня",
        "panel_view": "Вид панели",
        "results_view": "Вид результатов",
        "button_mode": "Режим кнопки (Только иконка)",
        "medium_mode": "Средний режим (Только кнопка)",
        "wide_mode": "Широкий режим (Строка поиска + иконка)",
        "extra_wide_mode": "Экстра широкий режим (Широкий + Заполнитель)",
        "list_view": "Вид списка",
        "tile_view": "Вид плитки",
        "list_icon_size": "Размер иконок списка",
        "tile_icon_size": "Размер иконок плитки",
        "panel_preview": "Предпросмотр панели",
        "results_preview": "Предпросмотр результатов",
        "application_1": "Приложение 1",
        "application_2": "Приложение 2",
        "file_txt": "Файл.txt",
        "file": "Файл",
        "category": "Категория",
        "path": "Путь",
        "general": "Общее",
        "profile": "Профиль",
        "profile_minimal": "Минимальный",
        "profile_developer": "Разработчик",
        "appearance": "Внешний вид",
        "keyboard_shortcuts": "Горячие клавиши",
        "open": "Открыть",
        "copy_path": "Копировать путь",
        "open_in_terminal": "Открыть в терминале",
        "move_to_trash": "Удалить в корзину",
        "open_location": "Открыть папку с файлом",
        "show_properties": "Свойства",
        "manage_app": "Управление приложением",
        "remove_from_history": "Удалить из истории",
        "reset_stats": "Сбросить статистику",
        "hint_applications": "Приложения",
        "hint_shell": "Выполнить команду",
        "hint_bookmarks": "Закладки",
        "hint_power": "Управление питанием",
        "hint_services": "Настройки системы",
        "hint_datetime": "Дата и время",
        "hint_define": "Определение слова",
        "hint_unit": "Конвертер величин",
        "hint_help": "Помощь и ярлыки",
        "man_not_installed": "Пакет Man не установлен"
    },
    "pt": {
        "search": "Pesquisar",
        "search_placeholder": "Pesquisar aqui",
        "start_searching": "Começar a pesquisar...",
        "search_dots": "Pesquisar...",
        "no_results": "Nenhum resultado encontrado",
        "type_to_search": "Digite para pesquisar",
        "recent_searches": "Pesquisas recentes",
        "clear_history": "Limpar histórico",
        "applications": "Aplicações",
        "other": "Outros",
        "today": "Hoje",
        "panel_view": "Visualização do painel",
        "results_view": "Visualização de resultados",
        "button_mode": "Modo botão (Apenas ícone)",
        "medium_mode": "Modo médio (Apenas botão)",
        "wide_mode": "Modo amplo (Barra de pesquisa + ícone)",
        "extra_wide_mode": "Modo extra amplo (Amplo + Espaço reservado)",
        "list_view": "Visualização em lista",
        "tile_view": "Visualização em blocos",
        "list_icon_size": "Tamanho do ícone da lista",
        "tile_icon_size": "Tamanho do ícone do bloco",
        "panel_preview": "Pré-visualização do painel",
        "results_preview": "Pré-visualização de resultados",
        "application_1": "Aplicação 1",
        "application_2": "Aplicação 2",
        "file_txt": "Arquivo.txt",
        "file": "Arquivo",
        "category": "Categoria",
        "path": "Caminho",
        "general": "Geral",
        "profile": "Perfil",
        "profile_minimal": "Mínimo",
        "profile_developer": "Desenvolvedor",
        "appearance": "Aparência",
        "keyboard_shortcuts": "Atalhos de teclado",
        "open": "Abrir",
        "copy_path": "Copiar caminho",
        "open_in_terminal": "Abrir no terminal",
        "move_to_trash": "Mover para o lixo",
        "open_location": "Abrir pasta recipiente",
        "show_properties": "Propriedades",
        "manage_app": "Gerir aplicação",
        "remove_from_history": "Remover do histórico",
        "reset_stats": "Redefinir estatísticas",
        "hint_applications": "Aplicações",
        "hint_shell": "Executar comando",
        "hint_bookmarks": "Marcadores",
        "hint_power": "Gestão de energia",
        "hint_services": "Configurações do sistema",
        "hint_datetime": "Data e Hora",
        "hint_define": "Definição de dicionário",
        "hint_unit": "Conversor de unidades",
        "hint_help": "Ajuda e atalhos",
        "man_not_installed": "O pacote Man não está instalado"
    },
    "ja": {
        "search": "検索",
        "search_placeholder": "ここで検索",
        "start_searching": "検索を開始...",
        "search_dots": "検索...",
        "no_results": "結果が見つかりません",
        "type_to_search": "入力して検索を開始",
        "recent_searches": "最近の検索",
        "clear_history": "履歴を消去",
        "applications": "アプリケーション",
        "other": "その他",
        "today": "今日",
        "panel_view": "パネル表示",
        "results_view": "結果表示",
        "button_mode": "ボタンモード (アイコンのみ)",
        "medium_mode": "中モード (ボタンのみ)",
        "wide_mode": "ワイドモード (検索バー + アイコン)",
        "extra_wide_mode": "エクストラワイドモード (ワイド + プレースホルダー)",
        "list_view": "リスト表示",
        "tile_view": "タイル表示",
        "list_icon_size": "リストアイコンサイズ",
        "tile_icon_size": "タイルアイコンサイズ",
        "panel_preview": "パネルプレビュー",
        "results_preview": "結果プレビュー",
        "application_1": "アプリケーション 1",
        "application_2": "アプリケーション 2",
        "file_txt": "ファイル.txt",
        "file": "ファイル",
        "category": "カテゴリ",
        "path": "パス",
        "general": "一般",
        "profile": "プロファイル",
        "profile_minimal": "ミニマル",
        "profile_developer": "開発者",
        "appearance": "外観",
        "keyboard_shortcuts": "キーボードショートカット",
        "open": "開く",
        "copy_path": "パスをコピー",
        "open_in_terminal": "ターミナルで開く",
        "move_to_trash": "ゴミ箱に移動",
        "open_location": "保存先フォルダを開く",
        "show_properties": "プロパティ",
        "manage_app": "アプリケーションの管理",
        "remove_from_history": "履歴から削除",
        "reset_stats": "統計をリセット",
        "hint_applications": "アプリケーション",
        "hint_shell": "コマンドを実行",
        "hint_bookmarks": "ブックマーク",
        "hint_power": "電源管理",
        "hint_services": "システム設定",
        "hint_datetime": "日付と時刻",
        "hint_define": "辞書定義",
        "hint_unit": "単位変換",
        "hint_help": "ヘルプとショートカット",
        "man_not_installed": "Manパッケージがインストールされていません"
    },
    "it": {
        "search": "Cerca",
        "search_placeholder": "Cerca qui",
        "start_searching": "Inizia la ricerca...",
        "no_results": "Nessun risultato",
        "type_to_search": "Digita per cercare",
        "recent_searches": "Ricerche recenti",
        "clear_history": "Cancella cronologia",
        "applications": "Applicazioni",
        "other": "Altro",
        "today": "Oggi",
        "list_view": "Vista Elenco",
        "tile_view": "Vista Griglia",
        "general": "Generale",
        "profile": "Profilo",
        "appearance": "Aspetto",
        "pinned_items": "Elementi Fissati",
        "pin_item": "Fissa",
        "unpin_item": "Rimuovi",
        "category_settings": "Impostazioni Categoria",
        "files": "File",
        "documents": "Documenti",
        "folders": "Cartelle",
        "web": "Web",
        "open": "Apri",
        "copy_path": "Copia Percorso",
        "open_in_terminal": "Apri nel Terminale",
        "move_to_trash": "Sposta nel Cestino",
        "open_location": "Apri Cartella Contenente",
        "show_properties": "Proprietà",
        "manage_app": "Gestisci Applicazione",
        "remove_from_history": "Rimuovi dalla Cronologia",
        "reset_stats": "Reimposta Statistiche",
        "hint_applications": "Applicazioni",
        "hint_shell": "Esegui comando",
        "hint_bookmarks": "Segnalibri",
        "hint_power": "Gestione Alimentazione",
        "hint_services": "Impostazioni di Sistema",
        "hint_datetime": "Data e Ora",
        "hint_define": "Definizione Dizionario",
        "hint_unit": "Convertitore Unità",
        "hint_help": "Aiuto e Scorciatoie",
        "man_not_installed": "Il pacchetto Man non è installato"
    },
    "el": {
        "search": "Αναζήτηση",
        "search_placeholder": "Αναζήτηση εδώ",
        "start_searching": "Έναρξη αναζήτησης...",
        "no_results": "Δεν βρέθηκαν αποτελέσματα",
        "type_to_search": "Πληκτρολογήστε για αναζήτηση",
        "recent_searches": "Πρόσφατες αναζητήσεις",
        "clear_history": "Εκκαθάριση ιστορικού",
        "applications": "Εφαρμογές",
        "other": "Άλλα",
        "today": "Σήμερα",
        "list_view": "Προβολή λίστας",
        "tile_view": "Προβολή πλακιδίων",
        "general": "Γενικά",
        "profile": "Προφίλ",
        "appearance": "Εμφάνιση",
        "pinned_items": "Καρφιτσωμένα",
        "pin_item": "Καρφίτσωμα",
        "unpin_item": "Ξεκαρφίτσωμα",
        "category_settings": "Ρυθμίσεις Κατηγορίας",
        "files": "Αρχεία",
        "documents": "Έγγραφα",
        "folders": "Φάκελοι",
        "web": "Ιστός",
        "open": "Άνοιγμα",
        "copy_path": "Αντιγραφή διαδρομής",
        "open_in_terminal": "Άνοιγμα στο τερματικό",
        "move_to_trash": "Μετακίνηση στα απορρίμματα",
        "open_location": "Άνοιγμα φακέλου",
        "show_properties": "Ιδιότητες",
        "manage_app": "Διαχείριση εφαρμογής",
        "remove_from_history": "Αφαίρεση από το ιστορικό",
        "reset_stats": "Επαναφορά στατιστικών",
        "hint_applications": "Εφαρμογές",
        "hint_shell": "Εκτέλεση εντολής",
        "hint_bookmarks": "Σελιδοδείκτες",
        "hint_power": "Διαχείριση ενέργειας",
        "hint_services": "Ρυθμίσεις συστήματος",
        "hint_datetime": "Ημερομηνία & Ώρα",
        "hint_define": "Ορισμός λεξικού",
        "hint_unit": "Μετατροπέας μονάδων",
        "hint_help": "Βοήθεια & Συντομεύσεις",
        "man_not_installed": "Το πακέτο Man δεν είναι εγκατεστημένο"
    },
    "az": {
        "search": "Axtar",
        "search_placeholder": "Burada axtar",
        "start_searching": "Axtarışa başla...",
        "no_results": "Nəticə tapılmadı",
        "type_to_search": "Axtarmaq üçün yazın",
        "recent_searches": "Son axtarışlar",
        "clear_history": "Tarixçəni təmizlə",
        "applications": "Tətbiqlər",
        "other": "Digər",
        "today": "Bu gün",
        "list_view": "Siyahı görünüşü",
        "tile_view": "Plitə görünüşü",
        "general": "Ümumi",
        "profile": "Profil",
        "appearance": "Görünüş",
        "pinned_items": "Sabitlənmişlər",
        "pin_item": "Sabitlə",
        "unpin_item": "Sabitləməni qaldır",
        "category_settings": "Kateqoriya Tənzimləmələri",
        "files": "Fayllar",
        "documents": "Sənədlər",
        "folders": "Qovluqlar",
        "web": "Veb",
        "open": "Aç",
        "copy_path": "Yolu kopyala",
        "open_in_terminal": "Terminalda aç",
        "move_to_trash": "Zibil qutusuna daşı",
        "open_location": "Qovluğu aç",
        "show_properties": "Xüsusiyyətlər",
        "manage_app": "Tətbiqi idarə et",
        "remove_from_history": "Tarixçədən sil",
        "reset_stats": "Statistikanı sıfırla",
        "hint_applications": "Tətbiqlər",
        "hint_shell": "Əmr icra et",
        "hint_bookmarks": "Əlfəcinlər",
        "hint_power": "Güc idarəetməsi",
        "hint_services": "Sistem tənzimləmələri",
        "hint_datetime": "Tarix və Saat",
        "hint_define": "Lüğət tərifi",
        "hint_unit": "Vahid çevirici",
        "hint_help": "Kömək və Qısayollar",
        "man_not_installed": "Man paketi quraşdırılmayıb"
    },
    "zh": {
        "search": "搜索",
        "search_placeholder": "在此搜索",
        "start_searching": "开始搜索...",
        "no_results": "未找到结果",
        "type_to_search": "输入以搜索",
        "recent_searches": "最近搜索",
        "clear_history": "清除历史",
        "applications": "应用程序",
        "other": "其他",
        "today": "今天",
        "list_view": "列表视图",
        "tile_view": "平铺视图",
        "general": "常规",
        "profile": "配置文件",
        "appearance": "外观",
        "pinned_items": "固定项目",
        "pin_item": "固定",
        "unpin_item": "取消固定",
        "category_settings": "类别设置",
        "files": "文件",
        "documents": "文档",
        "folders": "文件夹",
        "web": "网络",
        "open": "打开",
        "copy_path": "复制路径",
        "open_in_terminal": "在终端打开",
        "move_to_trash": "移至回收站",
        "open_location": "打开所在文件夹",
        "show_properties": "属性",
        "manage_app": "管理应用程序",
        "remove_from_history": "从历史记录移除",
        "reset_stats": "重置统计",
        "hint_applications": "应用程序",
        "hint_shell": "运行命令",
        "hint_bookmarks": "书签",
        "hint_power": "电源管理",
        "hint_services": "系统设置",
        "hint_datetime": "日期和时间",
        "hint_define": "字典定义",
        "hint_unit": "单位转换器",
        "hint_help": "帮助与快捷键",
        "man_not_installed": "未安装 Man 包"
    },
    "hy": {
        "search": "Որոնել",
        "search_placeholder": "Որոնել այստեղ",
        "start_searching": "Սկսել որոնումը...",
        "no_results": "Արդյունքներ չեն գտնվել",
        "type_to_search": "Մուտքագրեք որոնման համար",
        "recent_searches": "Վերջին որոնումները",
        "clear_history": "Մաքրել պատմությունը",
        "applications": "Ծրագրեր",
        "other": "Այլ",
        "today": "Այսօր",
        "list_view": "Ցուցակի տեսք",
        "tile_view": "Սալիկների տեսք",
        "general": "Ընդհանուր",
        "profile": "Պրոֆիլ",
        "appearance": "Տեսք",
        "pinned_items": "Ամրացվածներ",
        "pin_item": "Ամրացնել",
        "unpin_item": "Ապամրացնել",
        "category_settings": "Կատեգորիայի կարգավորումներ",
        "files": "Ֆայլեր",
        "documents": "Փաստաթղթեր",
        "folders": "Պանակներ",
        "web": "Վեբ",
        "open": "Բացել",
        "copy_path": "Պատճենել ուղին",
        "open_in_terminal": "Բացել տերմինալում",
        "move_to_trash": "Տեղափոխել աղբարկղ",
        "open_location": "Բացել պանակը",
        "show_properties": "Հատկություններ",
        "manage_app": "Կառավարել ծրագիրը",
        "remove_from_history": "Հեռացնել պատմությունից",
        "reset_stats": "Վերականգնել վիճակագրությունը",
        "hint_applications": "Ծրագրեր",
        "hint_shell": "Կատարել հրաման",
        "hint_bookmarks": "Էջանիշներ",
        "hint_power": "Սնուցման կառավարում",
        "hint_services": "Համակարգի կարգավորումներ",
        "hint_datetime": "Ամսաթիվ և ժամ",
        "hint_define": "Բառարանի սահմանում",
        "hint_unit": "Միավորների փոխարկիչ",
        "hint_help": "Օգնություն և դյուրանցումներ",
        "man_not_installed": "Man փաթեթը տեղադրված չէ"
    },
    "hi": {
        "search": "खोजें",
        "search_placeholder": "यहाँ खोजें",
        "start_searching": "खोजना शुरू करें...",
        "no_results": "कोई परिणाम नहीं मिला",
        "type_to_search": "खोजने के लिए टाइप करें",
        "recent_searches": "हाल की खोजें",
        "clear_history": "इतिहास मिटाएं",
        "applications": "अनुप्रयोग",
        "other": "अन्य",
        "today": "आज",
        "list_view": "सूची दृश्य",
        "tile_view": "टाइल्स दृश्य",
        "general": "सामान्य",
        "profile": "प्रोफ़ाइल",
        "appearance": "दिखावट",
        "pinned_items": "पिन की गई वस्तुएं",
        "pin_item": "पिन करें",
        "unpin_item": "अनपिन करें",
        "category_settings": "श्रेणी सेटिंग्स",
        "files": "फ़ाइलें",
        "documents": "दस्तावेज़",
        "folders": "फ़ोल्डर्स",
        "web": "वेब",
        "open": "खोलें",
        "copy_path": "पथ कॉपी करें",
        "open_in_terminal": "टर्मिनल में खोलें",
        "move_to_trash": "ट्रैश में ले जाएं",
        "open_location": "फ़ोल्डर खोलें",
        "show_properties": "गुण",
        "manage_app": "एप्लिकेशन प्रबंधित करें",
        "remove_from_history": "इतिहास से हटाएं",
        "reset_stats": "आंकड़े रीसेट करें",
        "hint_applications": "अनुप्रयोग",
        "hint_shell": "कमांड चलाएं",
        "hint_bookmarks": "बुकमार्क",
        "hint_power": "पावर प्रबंधन",
        "hint_services": "सिस्टम सेटिंग्स",
        "hint_datetime": "दिनांक और समय",
        "hint_define": "शब्दकोश परिभाषा",
        "hint_unit": "इकाई परिवर्तक",
        "hint_help": "सहायता और शॉर्टकट",
        "man_not_installed": "Man पैकेज स्थापित नहीं है"
    },
    "bn": {
        "search": "অনুসন্ধান",
        "search_placeholder": "এখানে অনুসন্ধান করুন",
        "start_searching": "অনুসন্ধান শুরু করুন...",
        "no_results": "কোন ফলাফল পাওয়া যায়নি",
        "type_to_search": "অনুসন্ধান করতে টাইপ করুন",
        "recent_searches": "সাম্প্রতিক অনুসন্ধান",
        "clear_history": "ইতিহাস মুছুন",
        "applications": "অ্যাপ্লিকেশন",
        "other": "অন্যান্য",
        "today": "আজ",
        "list_view": "তালিকা ভিউ",
        "tile_view": "টাইল ভিউ",
        "general": "সাধারণ",
        "profile": "প্রোফাইল",
        "appearance": "চেহারা",
        "pinned_items": "পিন করা আইটেম",
        "pin_item": "পিন করুন",
        "unpin_item": "আনপিন করুন",
        "category_settings": "বিভাগ সেটিংস",
        "files": "ফাইল",
        "documents": "নথি",
        "folders": "ফোল্ডার",
        "web": "ওয়েব",
        "open": "খুলুন",
        "copy_path": "পাথ কপি করুন",
        "open_in_terminal": "টার্মিনালে খুলুন",
        "move_to_trash": "ট্র্যাশে সরান",
        "open_location": "ফোল্ডার খুলুন",
        "show_properties": "বৈশিষ্ট্য",
        "manage_app": "অ্যাপ্লিকেশন পরিচালনা করুন",
        "remove_from_history": "ইতিহাস থেকে সরান",
        "reset_stats": "পরিসংখ্যান পুনরায় সেট করুন",
        "hint_applications": "অ্যাপ্লিকেশন",
        "hint_shell": "কমান্ড চালান",
        "hint_bookmarks": "বুকমার্কস",
        "hint_power": "পাওয়ার ম্যানেজমেন্ট",
        "hint_services": "সিস্টেম সেটিংস",
        "hint_datetime": "তারিখ এবং সময়",
        "hint_define": "অভিধান সংজ্ঞা",
        "hint_unit": "ইউনিট কনভার্টার",
        "hint_help": "সহায়তা এবং শর্টকাটস",
        "man_not_installed": "Man প্যাকেজ ইনস্টল করা নেই"
    },
    "ur": {
        "search": "تلاش",
        "search_placeholder": "یہاں تلاش کریں",
        "start_searching": "تلاش شروع کریں...",
        "no_results": "کوئی نتائج نہیں ملے",
        "type_to_search": "تلاش کرنے کے لئے لکھیں",
        "recent_searches": "حالیہ تلاشیں",
        "clear_history": "تاریخ صاف کریں",
        "applications": "ایپلی کیشنز",
        "other": "دیگر",
        "today": "آج",
        "list_view": "فہرست کا منظر",
        "tile_view": "ٹائل کا منظر",
        "general": "عام",
        "profile": "پروفائل",
        "appearance": "ظاہری شکل",
        "pinned_items": "پِن شدہ اشیاء",
        "pin_item": "پِن کریں",
        "unpin_item": "ان پِن کریں",
        "category_settings": "زمرہ کی ترتیبات",
        "files": "فائلیں",
        "documents": "دستاویزات",
        "folders": "فولڈرز",
        "web": "ویب",
        "open": "کھولیں",
        "copy_path": "راستہ کاپی کریں",
        "open_in_terminal": "ٹرمینل میں کھولیں",
        "move_to_trash": "ردی کی ٹوکری میں منتقل کریں",
        "open_location": "فولڈر کھولیں",
        "show_properties": "خصوصیات",
        "manage_app": "ایپلیکیشن کا انتظام کریں",
        "remove_from_history": "تاریخ سے ہٹائیں",
        "reset_stats": "اعداد و شمار کو دوبارہ ترتیب دیں",
        "hint_applications": "ایپلی کیشنز",
        "hint_shell": "کمانڈ چلائیں",
        "hint_bookmarks": "بُک مارکس",
        "hint_power": "پاور مینجمنٹ",
        "hint_services": "سسٹم کی ترتیبات",
        "hint_datetime": "تاريخ اور وقت",
        "hint_define": "لغت کی تعریف",
        "hint_unit": "یونٹ کنورٹر",
        "hint_help": "مدد اور شارٹ کٹس",
        "man_not_installed": "Man پیکیج انسٹال نہیں ہے"
    },
    "id": {
        "search": "Cari",
        "search_placeholder": "Cari di sini",
        "start_searching": "Mulai mencari...",
        "no_results": "Tidak ada hasil",
        "type_to_search": "Ketik untuk mencari",
        "recent_searches": "Pencarian Terbaru",
        "clear_history": "Hapus Riwayat",
        "applications": "Aplikasi",
        "other": "Lainnya",
        "today": "Hari ini",
        "list_view": "Tampilan Daftar",
        "tile_view": "Tampilan Grid",
        "general": "Umum",
        "profile": "Profil",
        "appearance": "Tampilan",
        "pinned_items": "Item Tersemat",
        "pin_item": "Sematkan",
        "unpin_item": "Lepaskan",
        "category_settings": "Pengaturan Kategori",
        "files": "Berkas",
        "documents": "Dokumen",
        "folders": "Folder",
        "web": "Web",
        "open": "Buka",
        "copy_path": "Salin Jalur",
        "open_in_terminal": "Buka di Terminal",
        "move_to_trash": "Pindahkan ke Sampah",
        "open_location": "Buka Folder Berisi",
        "show_properties": "Properti",
        "manage_app": "Kelola Aplikasi",
        "remove_from_history": "Hapus dari Riwayat",
        "reset_stats": "Atur Ulang Statistik",
        "hint_applications": "Aplikasi",
        "hint_shell": "Jalankan Perintah",
        "hint_bookmarks": "Penanda",
        "hint_power": "Manajemen Daya",
        "hint_services": "Pengaturan Sistem",
        "hint_datetime": "Tanggal & Waktu",
        "hint_define": "Definisi Kamus",
        "hint_unit": "Konverter Unit",
        "hint_help": "Bantuan & Pintasan",
        "man_not_installed": "Paket Man tidak terinstal"
    },
    "fa": {
        "search": "جستجو",
        "search_placeholder": "اینجا جستجو کنید",
        "start_searching": "شروع جستجو...",
        "no_results": "نتیجه‌ای یافت نشد",
        "type_to_search": "برای جستجو تایپ کنید",
        "recent_searches": "جستجوهای اخیر",
        "clear_history": "پاک کردن تاریخچه",
        "applications": "برنامه‌ها",
        "other": "دیگر",
        "today": "امروز",
        "list_view": "نمای لیست",
        "tile_view": "نمای کاشی",
        "general": "عمومی",
        "profile": "پروفایل",
        "appearance": "ظاهر",
        "pinned_items": "موارد سنجاق شده",
        "pin_item": "سنجاق کردن",
        "unpin_item": "برداشتن سنجاق",
        "category_settings": "تنظیمات دسته‌بندی",
        "files": "فایل‌ها",
        "documents": "اسناد",
        "folders": "پوشه‌ها",
        "web": "وب",
        "open": "باز کردن",
        "copy_path": "کپی مسیر",
        "open_in_terminal": "باز کردن در ترمینال",
        "move_to_trash": "انتقال به زباله‌دان",
        "open_location": "باز کردن پوشه",
        "show_properties": "ویژگی‌ها",
        "manage_app": "مدیریت برنامه",
        "remove_from_history": "حذف از تاریخچه",
        "reset_stats": "بازنشانی آمار",
        "hint_applications": "برنامه‌ها",
        "hint_shell": "اجرای دستور",
        "hint_bookmarks": "نشانک‌ها",
        "hint_power": "مدیریت انرژی",
        "hint_services": "تنظیمات سیستم",
        "hint_datetime": "تاریخ و زمان",
        "hint_define": "تعریف فرهنگ لغت",
        "hint_unit": "مبدل واحد",
        "hint_help": "راهنما و میانبرها",
        "man_not_installed": "بسته Man نصب نشده است"
    }
}